trigger:
- master
resources:
- repo: self
variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build and Push image
  jobs:
   - job: Build
     displayName: Build and Push
     pool:
        vmImage: 'ubuntu-latest'
     steps:
      - task: Docker@2
        inputs:
           containerRegistry: 'Dockerhub'
           repository: 'pskitsme92/TestAutomation'
           command: 'buildAndPush'
           Dockerfile: '**/Dockerfile'
      - task: CopyFiles@2
        inputs:
           Contents: 'docker-compose.yml'
           TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
           PathtoPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'
      - powershell:
         Write-Host "PSK1 PSK2 PSK3 "
